name: fire_smoke_seg
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.7
  - pillow
  - tqdm
  - pip:
      - numpy
      - scikit-learn
      - matplotlib
      - onnx
      - onnxruntime
      - tensorboard
      - albumentations
      - opencv-python

