name: smoke100k
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aom=3.6.0
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - cairo=1.16.0
  - cudatoolkit=11.7.1
  - dav1d=1.2.1
  - deprecated=1.2.13
  - expat=2.7.1
  - ffmpeg=6.1.1
  - filelock=3.17.0
  - fontconfig=2.14.1
  - freetype=2.13.3
  - fsspec=2025.3.2
  - giflib=5.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.1
  - importlib-metadata=8.5.0
  - intel-openmp=2023.1.0
  - jinja2=3.1.6
  - jpeg=9e
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - leptonica=1.82.0
  - lerc=4.0.0
  - libabseil=20250127.0
  - libarchive=3.7.7
  - libdeflate=1.22
  - libffi=3.4.4
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libglib=2.78.4
  - libgomp=15.1.0
  - libiconv=1.16
  - libogg=1.3.5
  - libopus=1.3.1
  - libpng=1.6.39
  - libprotobuf=5.29.3
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libtheora=1.1.1
  - libtiff=4.7.0
  - libtorch=2.5.1
  - libuuid=1.41.5
  - libuv=1.48.0
  - libvorbis=1.3.7
  - libvpx=1.13.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxml2=2.13.8
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.4
  - networkx=3.4.2
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.0.16
  - opentelemetry-api=1.30.0
  - pcre2=10.42
  - pillow=11.1.0
  - pip=25.1
  - pixman=0.40.0
  - pthread-stubs=0.3
  - python=3.10.18
  - pytorch=2.5.1
  - readline=8.2
  - setuptools=78.1.1
  - sleef=3.5.1
  - sqlite=3.45.3
  - sympy=1.13.3
  - tbb=2021.8.0
  - tesseract=5.2.0
  - tk=8.6.14
  - torchaudio=2.5.1
  - torchvision=0.20.1
  - tqdm=4.67.1
  - typing_extensions=4.12.2
  - wheel=0.45.1
  - wrapt=1.17.0
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.6.4
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - absl-py==2.2.2
      - albucore==0.0.24
      - albumentations==2.0.8
      - annotated-types==0.7.0
      - astunparse==1.6.3
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - coloredlogs==15.0.1
      - contourpy==1.3.2
      - coverage==7.10.6
      - cycler==0.12.1
      - exceptiongroup==1.3.0
      - flatbuffers==25.2.10
      - fonttools==4.58.0
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.71.0
      - h5py==3.14.0
      - humanfriendly==10.0
      - idna==3.10
      - iniconfig==2.1.0
      - joblib==1.5.0
      - keras==3.11.3
      - kiwisolver==1.4.8
      - libclang==18.1.1
      - markdown==3.8
      - markdown-it-py==4.0.0
      - matplotlib==3.10.3
      - mdurl==0.1.2
      - ml-dtypes==0.5.3
      - namex==0.1.0
      - numpy==2.2.6
      - onnx==1.18.0
      - onnxruntime==1.22.0
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - opt-einsum==3.4.0
      - optree==0.17.0
      - packaging==25.0
      - pandas==2.3.2
      - pluggy==1.6.0
      - protobuf==6.32.0
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - pygments==2.19.2
      - pyparsing==3.2.3
      - pytest==8.4.1
      - pytest-cov==6.2.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - requests==2.32.5
      - rich==14.1.0
      - scikit-learn==1.7.0
      - scipy==1.15.3
      - simsimd==6.2.1
      - six==1.17.0
      - stringzilla==3.12.5
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - tomli==2.2.1
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - werkzeug==3.1.3
